---
- hosts: all
  tasks:
    - lineinfile: dest="~/.bash_profile" state=present create=yes
        line="set -o vi"

    - lineinfile: dest="~/.bash_profile" state=present create=yes
        line="export PS1='$(__git_ps1) \W\$ '"

    - file: src={{ curdir }}/files/screenrc dest=~/.screenrc state=link

    - lineinfile: dest="~/.bashrc" state=present create=yes
        line="export TERMCAP=$(echo $TERMCAP | sed -e 's/Co#8/Co#256/g')"
