---
- hosts: all
  tasks:
    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim
        # version: v0.10.2

    - file: path=~/.vim/spell state=directory

    - command: vim -i NONE -c PluginUpdate -c quitall
    # FIXME: compile https://github.com/Shougo/vimproc.vim
